### ISSUE TITLE
scipion3 not found

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-installer#12]
**Steps to reproduce:**
```
installscipion -conda -dev ~/git/scipion3 -httpsClone
cd git/scipion3/xmipp-bundle
conda activate .scipion3env
./xmipp 
```
results in 
` No scipion3 found. If you intended to use Xmipp in the Scipion framework, check the binding at SCIPION_HOME/software/binding...`

**Expectation:**
Scipion3 should be in the environment path. No error should be reported

**Comment by pconesa** [comment]
Do you expect to have SCIPION_HOME define when you activate the environment?
It would be nice ... Is it possible?

Do you mean something else?

**Comment by dmaluenda** [comment]
We can link the scipion3 script in the environ/bin in order to get ot visible when the environ is actived.

On the other hand, an alternative is to run xmipp by using the scipion3 as wraper, just after the installation (no activation is needed):

`./scipion3 run xmipp-bundle/xmipp [args]`

In this way, the wraper activates the environ and properly sets the env.vars. for the xmipp command.

**Comment by DStrelak** [comment]
I think it would be cleaner to have Scipion home set in the environment, but I'll leave it up to you.

**Comment by dmaluenda** [comment]
Is it possible to set an enviromemtal variable while activating the virtualenv? TBH, I don't know. But if possible, it makes sense.

On the other hand, I think linking the scipion3 launcher in the env/bin also makes sense.

However, the 'usual' way to run commands under scipion's environ is by using the wrapper 'scipion3 run'.

**Comment by pconesa** [comment]
This is a developer issue. I do not expect regular users to activate the environment.

As developers....there are many ways to do this, once you know it.
